# Generated by Django 4.1.2 on 2023-01-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_remove_orders_price_ordered_items_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
