# Generated by Django 4.1.2 on 2023-01-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_items_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_id',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
